language: python
os: linux
dist: bionic
sudo: required

matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.6           # this works for Linux but is ignored on macOS or Windows
#     - name: "Python 3.7.4 on macOS"
#       os: osx
#       osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
#       language: shell       # 'language: python' is an error on Travis CI macOS
#     - name: "Python 3.7.4 on Windows"
#       os: windows           # Windows 10.0.17134 N/A Build 17134
#       language: shell       # 'language: python' is an error on Travis CI Windows
#       before_install:
#         - choco install python
#         - python -m pip install --upgrade pip
#       env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
     
sudo: required

before_install:
# Install wine for packaging FlightDeck for Windows:
- sudo dpkg --add-architecture i386
- wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
- sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
- sudo apt-get update
- sudo apt-get install -y --install-recommends winehq-stable

- sudo apt-get install -y zip

install:
- pip3 install --upgrade pip
- ./ground.py build

script:
- echo "Tests will go here"

before_deploy:
  - ./ground.py deploy-linux
  - zip -r FlightDeck-linux-x64.zip ./ui/release-builds/FlightDeck-linux-x64
  - ./ground.py deploy-mac
  - zip -r FlightDeck-darwin-x64.zip ./ui/release-builds/FlightDeck-darwin-x64
  - ./ground.py deploy-win
  - zip -r FlightDeck-win32-x64.zip ./ui/release-builds/FlightDeck-win32-x64

  - git config --local user.name UAS@UCLA
  - git config --local user.email unmannedsystems.ucla@gmail.com
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: d09GH/Cz5+WUAmUCNkWI8L/T355VdjulzE+DwvpVFKMEx/NZbyJIBP2Qs+u7UkrZMw33SGAGSCSdPFksaYGYtGAdNVBKwvGqTGJyp4qxyx95Ro7vP79tsitk/+wfNxhPnjxnYkFRcE0EZ90/oZpAvnj1tdudSqnS104xAPV7ebWMZETqr8wNETu+mrrKM8rStFPW0KUmBFm+5SHvwajRTJivBMDxu02dtI769it/dZKGfROabHBZUw4an3Qxy0LM1RENrdNEThIQyMYtWSFa81FKlIwQqCxt2BKnyISENBkPz29sd9TIUYfHPVYs5viaC5aDj5tta3kVXMYYdMNatyHUnBpHScoV6P+BFeOltgnWQfUBc7xOfSwn8+B2QgEnPpt6Jit/InQ+PwCBO4SkExU0KhMQy8+5kLR19sTxibmnqpXusS4RrghLaXWzBjkpmyUlVr5GbPCwDACEIDijA90/NEQ0brxPX5JWA1ipvC4HdFzQmpW4/B0F6PA4DDQs5YUNmXpcTKLBHSdE3laAZRF9zf2xri4c+1cKYbNH4rkJlrLLJFr6QtR0i0Njewf56MzMgSf+7d3OlwwrBnHj2vp2sD3uaLk1iWNJe4VE5pXvgh9KeB24TNpfnTrpsXlKHhi7QsKt7Pex7JnhOTANjosPlR7rF8JZ8NPHC/U4pUY=
  file:
    - "FlightDeck-darwin-x64.zip"
    - "FlightDeck-linux-x64.zip"
    - "FlightDeck-win32-x64.zip"
#   on:
#     repo: uas-at-ucla/ground-station
#     branch: 
#       only: 
#         - alfred
  skip_cleanup: true
  draft: true
