language: python
os: linux
sudo: required

python:
- '3.6'

# before_install:
# - sudo apt-get update
# - sudo apt-get install -y wine64 # for packaging FlightDeck for Windows

install:
- ./ground.py build

script:
- lscpu
- ./ground.py deploy-linux
- ./ground.py deploy-mac
- ./ground.py deploy-win
