language: python
matrix:
  include:
    -name: "linux"
     python: 3.6
    -name: "mac"
     os: osx
     osx_image: xcode11
     language: shell
     
sudo: required

install:
- pip3 install --upgrade pip
- ./ground.py build

script:
- true
