language: python
os: linux
dist: bionic
sudo: required

matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.6           # this works for Linux but is ignored on macOS or Windows
#     - name: "Python 3.7.4 on macOS"
#       os: osx
#       osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
#       language: shell       # 'language: python' is an error on Travis CI macOS
#     - name: "Python 3.7.4 on Windows"
#       os: windows           # Windows 10.0.17134 N/A Build 17134
#       language: shell       # 'language: python' is an error on Travis CI Windows
#       before_install:
#         - choco install python
#         - python -m pip install --upgrade pip
#       env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
     
sudo: required

before_install:
# Install wine for packaging FlightDeck for Windows:
- sudo dpkg --add-architecture i386
- wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
- sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
- sudo apt-get update
- sudo apt-get install -y --install-recommends winehq-stable

install:
- pip3 install --upgrade pip
- ./ground.py build

script:
- ./ground.py deploy-linux
- ./ground.py deploy-mac
- ./ground.py deploy-win
- ls ui/release-builds

deploy:
  provider: releases
  api_key: "b9bdce6d160c3a75ddf9cb52ddcf099b7d86f1cb"
  file:
    - "./ui/release-builds/FlightDeck-darwin-x64"
    - "./ui/release-builds/FlightDeck-linux-x64"
    - "./ui/release-builds/FlightDeck-win32-x64"
  on:
    repo: uas-at-ucla/ground-station
    branch: 
      only: 
        - alfred
  skip_cleanup: true
  draft: true
