language: python
os: linux
dist: bionic
sudo: required

python:
- '3.6'

before_install:
# Install wine for packaging FlightDeck for Windows:
- sudo dpkg --add-architecture i386
- wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
- sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
- sudo apt-get update
- sudo apt-get install -y --install-recommends winehq-stable

install:
- ./ground.py build

script:
- ./ground.py deploy-linux
- ./ground.py deploy-mac
- ./ground.py deploy-win
